export enum TipoDevolucion {
  SIN_PROVEEDOR = 'SIN_PROVEEDOR',
  CON_PROVEEDOR = 'CON_PROVEEDOR',
}

export enum EstadoDevolucion {
  PENDIENTE = 'PENDIENTE',
  SEPARADO = 'SEPARADO',
  RETIRADO = 'RETIRADO',
  CANJEADO = 'CANJEADO',
  ACREDITADO = 'ACREDITADO',
  DESCARTADO = 'DESCARTADO',
  CANCELADA = 'CANCELADA',
}
